version: 2

jobs: # a collection of steps

  build: # runs not using Workflows must have a `build` job as entry point

    working_directory: ~/circleci/fixml-connection-test-tool

    steps: # a collection of executable commands

      - run: mvn clean package