version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: mvn clean package
	  - store_test_results:
			  path: test-results
	  - store_artifacts:
			  path: /home/circleci/project/target/fixml-connection-test-tool.zip
			  destination: zip