version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: mvn clean package
      - store_artifacts: 
          path: /home/circleci/project/target/fixml-connection-test-tool.zip
          destination: fixml-connection-test-tool.zip